/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.abn.demo.stream.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ExchangeTranslation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4926940198279613611L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExchangeTranslation\",\"namespace\":\"com.abn.demo.stream.model\",\"fields\":[{\"name\":\"exchange\",\"type\":\"string\",\"avro.java.string\":\"String\"},{\"name\":\"raw_exchange\",\"type\":\"string\",\"avro.java.string\":\"String\"},{\"name\":\"source\",\"type\":\"string\",\"avro.java.string\":\"String\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ExchangeTranslation> ENCODER =
      new BinaryMessageEncoder<ExchangeTranslation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ExchangeTranslation> DECODER =
      new BinaryMessageDecoder<ExchangeTranslation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ExchangeTranslation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ExchangeTranslation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ExchangeTranslation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ExchangeTranslation>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ExchangeTranslation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ExchangeTranslation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ExchangeTranslation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ExchangeTranslation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence exchange;
  private java.lang.CharSequence raw_exchange;
  private java.lang.CharSequence source;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExchangeTranslation() {}

  /**
   * All-args constructor.
   * @param exchange The new value for exchange
   * @param raw_exchange The new value for raw_exchange
   * @param source The new value for source
   */
  public ExchangeTranslation(java.lang.CharSequence exchange, java.lang.CharSequence raw_exchange, java.lang.CharSequence source) {
    this.exchange = exchange;
    this.raw_exchange = raw_exchange;
    this.source = source;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return exchange;
    case 1: return raw_exchange;
    case 2: return source;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: exchange = (java.lang.CharSequence)value$; break;
    case 1: raw_exchange = (java.lang.CharSequence)value$; break;
    case 2: source = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'exchange' field.
   * @return The value of the 'exchange' field.
   */
  public java.lang.CharSequence getExchange() {
    return exchange;
  }


  /**
   * Sets the value of the 'exchange' field.
   * @param value the value to set.
   */
  public void setExchange(java.lang.CharSequence value) {
    this.exchange = value;
  }

  /**
   * Gets the value of the 'raw_exchange' field.
   * @return The value of the 'raw_exchange' field.
   */
  public java.lang.CharSequence getRawExchange() {
    return raw_exchange;
  }


  /**
   * Sets the value of the 'raw_exchange' field.
   * @param value the value to set.
   */
  public void setRawExchange(java.lang.CharSequence value) {
    this.raw_exchange = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Creates a new ExchangeTranslation RecordBuilder.
   * @return A new ExchangeTranslation RecordBuilder
   */
  public static com.abn.demo.stream.model.ExchangeTranslation.Builder newBuilder() {
    return new com.abn.demo.stream.model.ExchangeTranslation.Builder();
  }

  /**
   * Creates a new ExchangeTranslation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ExchangeTranslation RecordBuilder
   */
  public static com.abn.demo.stream.model.ExchangeTranslation.Builder newBuilder(com.abn.demo.stream.model.ExchangeTranslation.Builder other) {
    if (other == null) {
      return new com.abn.demo.stream.model.ExchangeTranslation.Builder();
    } else {
      return new com.abn.demo.stream.model.ExchangeTranslation.Builder(other);
    }
  }

  /**
   * Creates a new ExchangeTranslation RecordBuilder by copying an existing ExchangeTranslation instance.
   * @param other The existing instance to copy.
   * @return A new ExchangeTranslation RecordBuilder
   */
  public static com.abn.demo.stream.model.ExchangeTranslation.Builder newBuilder(com.abn.demo.stream.model.ExchangeTranslation other) {
    if (other == null) {
      return new com.abn.demo.stream.model.ExchangeTranslation.Builder();
    } else {
      return new com.abn.demo.stream.model.ExchangeTranslation.Builder(other);
    }
  }

  /**
   * RecordBuilder for ExchangeTranslation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExchangeTranslation>
    implements org.apache.avro.data.RecordBuilder<ExchangeTranslation> {

    private java.lang.CharSequence exchange;
    private java.lang.CharSequence raw_exchange;
    private java.lang.CharSequence source;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.abn.demo.stream.model.ExchangeTranslation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.exchange)) {
        this.exchange = data().deepCopy(fields()[0].schema(), other.exchange);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.raw_exchange)) {
        this.raw_exchange = data().deepCopy(fields()[1].schema(), other.raw_exchange);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.source)) {
        this.source = data().deepCopy(fields()[2].schema(), other.source);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ExchangeTranslation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.abn.demo.stream.model.ExchangeTranslation other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.exchange)) {
        this.exchange = data().deepCopy(fields()[0].schema(), other.exchange);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.raw_exchange)) {
        this.raw_exchange = data().deepCopy(fields()[1].schema(), other.raw_exchange);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.source)) {
        this.source = data().deepCopy(fields()[2].schema(), other.source);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'exchange' field.
      * @return The value.
      */
    public java.lang.CharSequence getExchange() {
      return exchange;
    }


    /**
      * Sets the value of the 'exchange' field.
      * @param value The value of 'exchange'.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ExchangeTranslation.Builder setExchange(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.exchange = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'exchange' field has been set.
      * @return True if the 'exchange' field has been set, false otherwise.
      */
    public boolean hasExchange() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'exchange' field.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ExchangeTranslation.Builder clearExchange() {
      exchange = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'raw_exchange' field.
      * @return The value.
      */
    public java.lang.CharSequence getRawExchange() {
      return raw_exchange;
    }


    /**
      * Sets the value of the 'raw_exchange' field.
      * @param value The value of 'raw_exchange'.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ExchangeTranslation.Builder setRawExchange(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.raw_exchange = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'raw_exchange' field has been set.
      * @return True if the 'raw_exchange' field has been set, false otherwise.
      */
    public boolean hasRawExchange() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'raw_exchange' field.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ExchangeTranslation.Builder clearRawExchange() {
      raw_exchange = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ExchangeTranslation.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.source = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ExchangeTranslation.Builder clearSource() {
      source = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ExchangeTranslation build() {
      try {
        ExchangeTranslation record = new ExchangeTranslation();
        record.exchange = fieldSetFlags()[0] ? this.exchange : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.raw_exchange = fieldSetFlags()[1] ? this.raw_exchange : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.source = fieldSetFlags()[2] ? this.source : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ExchangeTranslation>
    WRITER$ = (org.apache.avro.io.DatumWriter<ExchangeTranslation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ExchangeTranslation>
    READER$ = (org.apache.avro.io.DatumReader<ExchangeTranslation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.exchange);

    out.writeString(this.raw_exchange);

    out.writeString(this.source);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.exchange = in.readString(this.exchange instanceof Utf8 ? (Utf8)this.exchange : null);

      this.raw_exchange = in.readString(this.raw_exchange instanceof Utf8 ? (Utf8)this.raw_exchange : null);

      this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.exchange = in.readString(this.exchange instanceof Utf8 ? (Utf8)this.exchange : null);
          break;

        case 1:
          this.raw_exchange = in.readString(this.raw_exchange instanceof Utf8 ? (Utf8)this.raw_exchange : null);
          break;

        case 2:
          this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










