/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.abn.demo.stream.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductTranslation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5414390078745856305L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductTranslation\",\"namespace\":\"com.abn.demo.stream.model\",\"fields\":[{\"name\":\"product\",\"type\":\"string\",\"avro.java.string\":\"String\"},{\"name\":\"raw_product\",\"type\":\"string\",\"avro.java.string\":\"String\"},{\"name\":\"source\",\"type\":\"string\",\"avro.java.string\":\"String\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductTranslation> ENCODER =
      new BinaryMessageEncoder<ProductTranslation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductTranslation> DECODER =
      new BinaryMessageDecoder<ProductTranslation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductTranslation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductTranslation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductTranslation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProductTranslation>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductTranslation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductTranslation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductTranslation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductTranslation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence product;
  private java.lang.CharSequence raw_product;
  private java.lang.CharSequence source;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductTranslation() {}

  /**
   * All-args constructor.
   * @param product The new value for product
   * @param raw_product The new value for raw_product
   * @param source The new value for source
   */
  public ProductTranslation(java.lang.CharSequence product, java.lang.CharSequence raw_product, java.lang.CharSequence source) {
    this.product = product;
    this.raw_product = raw_product;
    this.source = source;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return product;
    case 1: return raw_product;
    case 2: return source;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: product = (java.lang.CharSequence)value$; break;
    case 1: raw_product = (java.lang.CharSequence)value$; break;
    case 2: source = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'product' field.
   * @return The value of the 'product' field.
   */
  public java.lang.CharSequence getProduct() {
    return product;
  }


  /**
   * Sets the value of the 'product' field.
   * @param value the value to set.
   */
  public void setProduct(java.lang.CharSequence value) {
    this.product = value;
  }

  /**
   * Gets the value of the 'raw_product' field.
   * @return The value of the 'raw_product' field.
   */
  public java.lang.CharSequence getRawProduct() {
    return raw_product;
  }


  /**
   * Sets the value of the 'raw_product' field.
   * @param value the value to set.
   */
  public void setRawProduct(java.lang.CharSequence value) {
    this.raw_product = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Creates a new ProductTranslation RecordBuilder.
   * @return A new ProductTranslation RecordBuilder
   */
  public static com.abn.demo.stream.model.ProductTranslation.Builder newBuilder() {
    return new com.abn.demo.stream.model.ProductTranslation.Builder();
  }

  /**
   * Creates a new ProductTranslation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductTranslation RecordBuilder
   */
  public static com.abn.demo.stream.model.ProductTranslation.Builder newBuilder(com.abn.demo.stream.model.ProductTranslation.Builder other) {
    if (other == null) {
      return new com.abn.demo.stream.model.ProductTranslation.Builder();
    } else {
      return new com.abn.demo.stream.model.ProductTranslation.Builder(other);
    }
  }

  /**
   * Creates a new ProductTranslation RecordBuilder by copying an existing ProductTranslation instance.
   * @param other The existing instance to copy.
   * @return A new ProductTranslation RecordBuilder
   */
  public static com.abn.demo.stream.model.ProductTranslation.Builder newBuilder(com.abn.demo.stream.model.ProductTranslation other) {
    if (other == null) {
      return new com.abn.demo.stream.model.ProductTranslation.Builder();
    } else {
      return new com.abn.demo.stream.model.ProductTranslation.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductTranslation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductTranslation>
    implements org.apache.avro.data.RecordBuilder<ProductTranslation> {

    private java.lang.CharSequence product;
    private java.lang.CharSequence raw_product;
    private java.lang.CharSequence source;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.abn.demo.stream.model.ProductTranslation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.product)) {
        this.product = data().deepCopy(fields()[0].schema(), other.product);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.raw_product)) {
        this.raw_product = data().deepCopy(fields()[1].schema(), other.raw_product);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.source)) {
        this.source = data().deepCopy(fields()[2].schema(), other.source);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductTranslation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.abn.demo.stream.model.ProductTranslation other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.product)) {
        this.product = data().deepCopy(fields()[0].schema(), other.product);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.raw_product)) {
        this.raw_product = data().deepCopy(fields()[1].schema(), other.raw_product);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.source)) {
        this.source = data().deepCopy(fields()[2].schema(), other.source);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'product' field.
      * @return The value.
      */
    public java.lang.CharSequence getProduct() {
      return product;
    }


    /**
      * Sets the value of the 'product' field.
      * @param value The value of 'product'.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ProductTranslation.Builder setProduct(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.product = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'product' field has been set.
      * @return True if the 'product' field has been set, false otherwise.
      */
    public boolean hasProduct() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'product' field.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ProductTranslation.Builder clearProduct() {
      product = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'raw_product' field.
      * @return The value.
      */
    public java.lang.CharSequence getRawProduct() {
      return raw_product;
    }


    /**
      * Sets the value of the 'raw_product' field.
      * @param value The value of 'raw_product'.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ProductTranslation.Builder setRawProduct(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.raw_product = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'raw_product' field has been set.
      * @return True if the 'raw_product' field has been set, false otherwise.
      */
    public boolean hasRawProduct() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'raw_product' field.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ProductTranslation.Builder clearRawProduct() {
      raw_product = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ProductTranslation.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.source = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public com.abn.demo.stream.model.ProductTranslation.Builder clearSource() {
      source = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductTranslation build() {
      try {
        ProductTranslation record = new ProductTranslation();
        record.product = fieldSetFlags()[0] ? this.product : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.raw_product = fieldSetFlags()[1] ? this.raw_product : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.source = fieldSetFlags()[2] ? this.source : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductTranslation>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductTranslation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductTranslation>
    READER$ = (org.apache.avro.io.DatumReader<ProductTranslation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.product);

    out.writeString(this.raw_product);

    out.writeString(this.source);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.product = in.readString(this.product instanceof Utf8 ? (Utf8)this.product : null);

      this.raw_product = in.readString(this.raw_product instanceof Utf8 ? (Utf8)this.raw_product : null);

      this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.product = in.readString(this.product instanceof Utf8 ? (Utf8)this.product : null);
          break;

        case 1:
          this.raw_product = in.readString(this.raw_product instanceof Utf8 ? (Utf8)this.raw_product : null);
          break;

        case 2:
          this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










